countries = []
countries = CSV.read("corruption_2013.csv")
nations = []
countries.each do |country|
	nations << country[0..2]   
end
nations.flatten!



["Aruba",
"Andorra",
"Afghanistan",
"Angola",
"Albania",
"Andean Region",
"Arab World",
"United Arab Emirates",
"Argentina",
"Armenia",
"American Samoa",
"Antigua and Barbuda",
"Australia",
"Austria",
"Azerbaijan",
"Burundi",
"Belgium",
"Benin",
"Burkina Faso",
"Bangladesh",
"Bulgaria",
"Bahrain",
"Bahamas, The",
"Bosnia and Herzegovina",
"Belarus",
"Belize",
"Bermuda",
"Bolivia",
"Brazil",
"Barbados",
"Brunei Darussalam",
"Bhutan",
"Botswana",
"Sub-Saharan Africa",
"Central African Republic",
"Canada",
"East Asia and the Pacific",
"Europe and Central Asia",
"Switzerland",
"Channel Islands",
"Chile",
"China",
"Cote d'Ivoire",
"Latin America and the Caribbean",
"Middle East and North Africa",
"Cameroon",
"Congo, Rep.",
"Colombia",
"Comoros",
"Cabo Verde",
"Costa Rica",
"South Asia",
"Caribbean small states",
"Cuba",
"Curacao",
"Cayman Islands",
"Cyprus",
"Czech Republic",
"Germany",
"Djibouti",
"Dominica",
"Denmark",
"Dominican Republic",
"Algeria",
"East Asia & Pacific",
"East Asia & Pacific",
"Europe & Central Asia",
"Ecuador",
"Egypt",
"Euro area",
"Eritrea",
"Spain",
"Estonia",
"Ethiopia",
"European Union",
"Finland",
"Fiji",
"France",
"Faeroe Islands",
"Micronesia, Fed. Sts.",
"Gabon",
"United Kingdom",
"Georgia",
"Ghana",
"Guinea",
"Gambia, The",
"Guinea-Bissau",
"Equatorial Guinea",
"Greece",
"Grenada",
"Greenland",
"Guatemala",
"Guam",
"Guyana",
"High income",
"Hong Kong",
"Honduras",
"Croatia",
"Haiti",
"Hungary",
"Indonesia",
"Isle of Man",
"India",
"Ireland",
"Iran",
"Iraq",
"Iceland",
"Israel",
"Italy",
"Jamaica",
"Jordan",
"Japan",
"Kazakhstan",
"Kenya",
"Kyrgyz Republic",
"Cambodia",
"Kiribati",
"St. Kitts and Nevis",
"Korea, Rep.",
"Kosovo",
"Kuwait",
"Latin America & Caribbean",
"Lao",
"Lebanon",
"Liberia",
"Libya",
"St. Lucia",
"Latin America & Caribbean",
"Latin America and the Caribbean",
"Liechtenstein",
"Sri Lanka",
"Lesotho",
"Lithuania",
"Luxembourg",
"Latvia",
"Macao SAR, China",
"St. Martin",
"Morocco",
"Monaco",
"Moldova",
"Madagascar",
"Maldives",
"Mexico",
"Marshall Islands",
"Middle income",
"Macedonia",
"Mali",
"Malta",
"Myanmar",
"Montenegro",
"Mongolia",
"Northern Mariana Islands",
"Mozambique",
"Mauritania",
"Mauritius",
"Malawi",
"Malaysia",
"North America",
"Namibia",
"New Caledonia",
"Niger",
"Nigeria",
"Nicaragua",
"Netherlands",
"Norway",
"Nepal",
"New Zealand",
"Oman",
"Pakistan",
"Panama",
"Peru",
"Philippines",
"Palau",
"Papua New Guinea",
"Poland",
"Puerto Rico",
"Korea",
"Portugal",
"Paraguay",
"Pacific island small states",
"French Polynesia",
"Qatar",
"Romania",
"Russian Federation",
"Rwanda",
"South Asia",
"Saudi Arabia",
"Southern Cone Extended",
"Sudan",
"Senegal",
"Singapore",
"Solomon Islands",
"Sierra Leone",
"El Salvador",
"San Marino",
"Somalia",
"Serbia",
"Sub-Saharan Africa",
"South Sudan",
"Sao Tome and Principe",
"Suriname",
"Slovak Republic",
"Slovenia",
"Sweden",
"Swaziland",
"Sint Maarten",
"Seychelles",
"Syrian Arab Republic",
"Turks and Caicos Islands",
"Chad",
"Togo",
"Thailand",
"Tajikistan",
"Turkmenistan",
"Timor-Leste",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Tuvalu",
"Tanzania",
"Uganda",
"Ukraine",
"Uruguay",
"United States",
"Uzbekistan",
"St. Vincent and the Grenadines",
"Venezuela, RB",
"Virgin Islands",
"Vietnam",
"Vanuatu",
"West Bank and Gaza",
"World",
"Samoa",
"Yemen",
"South Africa",
"Congo, Dem. Rep.",
"Zambia",
"Zimbabwe"].each do |country|
  Country.create(name:country)
end


english = Language.create(name: "English")
spanish = Language.create(name: "Spanish")
french = Language.create(name: "French")

usa = Country.create(name: "USA", language_id: english.id)
spain = Country.create(name: "Spain", language_id: spanish.id)
france = Country.create(name: "France", language_id: french.id)

Phrase.create(language_id: english.id, hello: "hello", please: "please", thanks: "thanks", bathroom: "Where is the bathroom?")
Phrase.create(language_id: spanish.id, hello: "hola", please: "por favor", thanks: "gracias", bathroom: "Ou est trouvent les toilettes?")
Phrase.create(language_id: french.id, hello: "bonjour", please: "s'il vous plait", thanks: "merci", bathroom: "Donde esta el bano?")

Image.create(country_id: english.id, url: "http://www.scti.com.au/media/1059/travel-insurance-for-usa.jpg")
Image.create(country_id: english.id, url: "http://www.itesolcourse.com/images/location/usa-travel.jpg")
Image.create(country_id: english.id, url: "http://www.foley.com/files/Office/8766eedf-e4b8-42fe-9c37-4f8383686c0d/Presentation/OfficePhoto/washingtondc.jpg")
Image.create(country_id: english.id, url: "http://upload.wikimedia.org/wikipedia/commons/thumb/d/da/SF_From_Marin_Highlands3.jpg/1280px-SF_From_Marin_Highlands3.jpg")

Image.create(country_id: spain.id, url: "https://www.tripextras.com/files/countries/spain_basilicadelpilar.jpg")
Image.create(country_id: spain.id, url: "http://www.fodors.com/world/images/destinations/668/spain.jpg")
Image.create(country_id: spain.id, url: "http://www.fantom-xp.com/wallpapers/63/Travel_Spain.jpg")
Image.create(country_id: spain.id, url: "http://www.survivalspain.com/img/spain-travel-guide-homepage.jpg")

Image.create(country_id: france.id, url: "http://www.wallcoo.net/human/france/images/%5Bwallcoo%5D_france_travel_france_EF004.jpg")
Image.create(country_id: france.id, url: "http://traveldealslady.com/wp-content/uploads/Paris-France-travel-tour-traveltours-travel-agent-deals.jpg")
Image.create(country_id: france.id, url: "http://www.francetravelguide.com/files/2011/11/3952987239_3b29d282b5_z.jpg")
Image.create(country_id: france.id, url: "http://www.fodors.com/world/images/destinations/231/ile-de-france.jpg")


